//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NutritionalResearchBusiness.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FoodCategory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FoodCategory()
        {
            this.Foods = new HashSet<Foods>();
        }
    
        public System.Guid Id { get; set; }
        public string FirstCategoryCode { get; set; }
        public string FirstCategoryName { get; set; }
        public string SecondCategoryCode { get; set; }
        public string SecondCategoryName { get; set; }
        public System.DateTime CreationTime { get; set; }
        public string FoodUnit { get; set; }
        public string Description { get; set; }
        public string StatisticsCategoryCode { get; set; }
        public string StatisticsCategoryName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Foods> Foods { get; set; }
    }
}
