//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NutritionalResearchBusiness.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvestigationRecord
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InvestigationRecord()
        {
            this.InvestigationAnswer = new HashSet<InvestigationAnswer>();
            this.NutrtiveElementIntakeStatistics = new HashSet<NutrtiveElementIntakeStatistics>();
            this.StructureOfMeals = new HashSet<StructureOfMeals>();
        }
    
        public System.Guid Id { get; set; }
        public string QueueId { get; set; }
        public string HealthBookId { get; set; }
        public string Name { get; set; }
        public System.DateTime Birthday { get; set; }
        public int Week { get; set; }
        public int Stage { get; set; }
        public double Height { get; set; }
        public double BeforeWeight { get; set; }
        public double BeforeBMI { get; set; }
        public double CurrentWeight { get; set; }
        public string InvestigatorName { get; set; }
        public string AuditorName { get; set; }
        public int State { get; set; }
        public System.DateTime CreationTime { get; set; }
        public Nullable<System.DateTime> UpdatetionTime { get; set; }
        public Nullable<System.DateTime> AuditTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvestigationAnswer> InvestigationAnswer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NutrtiveElementIntakeStatistics> NutrtiveElementIntakeStatistics { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StructureOfMeals> StructureOfMeals { get; set; }
    }
}
