//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NutritionalResearchBusiness.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NutritionalResearchDatabaseEntities : DbContext
    {
        public NutritionalResearchDatabaseEntities()
            : base("name=NutritionalResearchDatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<FoodCategory> FoodCategory { get; set; }
        public virtual DbSet<FoodNutritions> FoodNutritions { get; set; }
        public virtual DbSet<Foods> Foods { get; set; }
        public virtual DbSet<InvestigationAnswer> InvestigationAnswer { get; set; }
        public virtual DbSet<InvestigationRecord> InvestigationRecord { get; set; }
        public virtual DbSet<NuritiveElement> NuritiveElement { get; set; }
        public virtual DbSet<NutrtiveElementIntakeStatistics> NutrtiveElementIntakeStatistics { get; set; }
        public virtual DbSet<Question> Question { get; set; }
        public virtual DbSet<ReferenceDiagram> ReferenceDiagram { get; set; }
        public virtual DbSet<StructureOfMeals> StructureOfMeals { get; set; }
    }
}
