//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NutritionalResearchBusiness.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class NuritiveElement
    {
        public System.Guid Id { get; set; }
        public string ChineseName { get; set; }
        public string EnglishName { get; set; }
        public string ChineseUnit { get; set; }
        public string EnglishUnit { get; set; }
        public Nullable<double> Stage1StandardValue { get; set; }
        public Nullable<double> Stage2StandardValue { get; set; }
        public Nullable<double> Stage3StandardValue { get; set; }
    }
}
