//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NutritionalResearchBusiness.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class StructureOfMeals
    {
        public System.Guid Id { get; set; }
        public System.Guid RecordId { get; set; }
        public string StructureDescription { get; set; }
        public double Intake { get; set; }
        public System.DateTime CreationTime { get; set; }
        public Nullable<System.DateTime> UpdationTime { get; set; }
        public string Unit { get; set; }
        public string StructureCode { get; set; }
    
        public virtual InvestigationRecord InvestigationRecord { get; set; }
    }
}
